### ISSUE TITLE
Remove any pep8 error from Course 1 and 2

### ISSUE THREAD

**Issue by huyvohcmc** [huyvohcmc/coursera-dsa#1]
Remove any pep8 error from Course 1 and 2.

**Comment by io-ma** [comment]
I can help you with this one.

**Comment by huyvohcmc** [comment]
@io-ma there are some PRs for it already.

**Comment by io-ma** [comment]
Ok, no problem. May I suggest you add a few comments on how to run the scripts in data-structures ( phone book one). 
Also, I would add those query functions inside the Query class then write a main function who would handle it all. 
Also instead of those input() I'd rather use sys.argv or even argparse ;-)
Ok, I will delete the fork then and move on to another project.
